import os
import itertools
import requests
from datetime import datetime

# ==========================================
# 1. THE LAYOUT TEMPLATE (DEFINED IN-FILE)
# ==========================================
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="google-site-verification" content="c_K6M_6ZUJTCpaExzxn5HyzwgyupoiwBwC2TUBi5RRg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{PLAYER_A}} vs {{PLAYER_B}} Advanced Stats, Role Comparison & Debate Matrix</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 text-slate-100 font-sans min-h-screen">

    <header class="border-b border-slate-800 bg-slate-950 p-4 sticky top-0 z-50">
        <div class="max-w-6xl mx-auto flex justify-between items-center">
            <span class="text-xl font-black tracking-wider text-emerald-400">📊 DEBATE.FC</span>
            <span class="text-xs text-slate-400 bg-slate-800 px-2 py-1 rounded">Auto-Updated Daily</span>
        </div>
    </header>

    <main class="max-w-4xl mx-auto px-4 py-8">
        <div class="text-center mb-10">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-800 text-xs font-semibold text-slate-400 mb-4 border border-slate-700">
                <span>🟢 { {{PLAYER_A_POS}} }</span>
                <span class="text-slate-600">vs</span>
                <span>🔵 { {{PLAYER_B_POS}} }</span>
            </div>
            <h1 class="text-3xl md:text-5xl font-extrabold tracking-tight mb-2">
                <span class="text-emerald-400">{{PLAYER_A}}</span> 
                <span class="text-slate-500 text-2xl md:text-3xl font-normal mx-2">vs</span> 
                <span class="text-cyan-400">{{PLAYER_B}}</span>
            </h1>
            <p class="text-slate-400 text-sm md:text-base">Role-weighted metric breakdown optimized for player tactical positions.</p>
        </div>

        <!-- Verdict Box -->
        <div class="bg-gradient-to-r from-emerald-950 to-slate-900 border border-emerald-500/30 rounded-xl p-6 mb-8 shadow-xl">
            <div class="flex items-center gap-2 mb-3">
                <span class="flex h-3 w-3 relative">
                    <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                    <span class="relative inline-flex rounded-full h-3 w-3 bg-emerald-500"></span>
                </span>
                <h2 class="text-xs font-bold uppercase tracking-widest text-emerald-400">Data-Engine Verdict</h2>
            </div>
            <p class="text-lg font-medium text-slate-200">{{VERDICT_TEXT}}</p>
        </div>

        <!-- Performance Bars Matrix -->
        <div class="bg-slate-950 border border-slate-800 rounded-xl p-6 mb-8 shadow-md">
            <div class="flex justify-between items-center mb-6 border-b border-slate-800 pb-3">
                <h3 class="text-sm font-bold uppercase tracking-widest text-slate-400">Performance Matrix (Per 90 Mins)</h3>
                <span class="text-[10px] text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20 font-bold uppercase tracking-wider">🌟 Role-Critical Metrics Highlighted</span>
            </div>
            
            <div class="space-y-6">
                {{STAT_ROWS}}
            </div>
        </div>

        <div class="text-center text-xs text-slate-500 mt-12">
            <p>Data scraped natively from open-source registries. Last compilation execution: {{TIMESTAMP}}</p>
            <p class="mt-2">Generated by DEBATE.FC Programmatic Network Engine.</p>
        </div>
    </main>
</body>
</html>
"""

# ==========================================
# 2. POSITION-AWARE DATA INGESTION
# ==========================================
POSITION_MAP = {2: "Defender", 3: "Midfielder", 4: "Forward"}

def fetch_live_fpl_pool():
    print("Connecting to live Premier League data registries...")
    url = "https://fantasy.premierleague.com/api/bootstrap-static/"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
    except Exception as e:
        print(f"Connection error: {e}. Utilizing local sandbox data pool instead.")
        return []

    all_players = data.get("elements", [])
    processed_players = []
    
    # Grab Defenders (2), Midfielders (3), and Forwards (4) with real game time
    for p in all_players:
        minutes = p.get("minutes", 0)
        pos_id = p.get("element_type")
        
        if pos_id in [2, 3, 4] and minutes > 600:
            match_segments = minutes / 90.0
            
            def per_90(field):
                try:
                    return round(float(p.get(field, 0)) / match_segments, 2)
                except (ValueError, TypeError):
                    return 0.0

            processed_players.append({
                "name": p.get("web_name"),
                "position_id": pos_id,
                "position_name": POSITION_MAP[pos_id],
                "goals": per_90("goals_scored"),
                "assists": per_90("assists"),
                "xg": per_90("expected_goals"),
                "xa": per_90("expected_assists"),
                "clean_sheets": per_90("clean_sheets"),
                "influence": per_90("influence"),
                "total_points": p.get("total_points", 0)
            })

    return sorted(processed_players, key=lambda x: x["total_points"], reverse=True)[:35]


# ==========================================
# 3. STAT ROW GENERATOR WITH POSITION INJECTION
# ==========================================
def build_metric_row(label, val_a, val_b, is_critical):
    total = (val_a + val_b) or 1.0
    pct_a = (val_a / total) * 100
    pct_b = (val_b / total) * 100

    # Highlight style adjustments based on role importance
    row_border = "border-l-4 border-emerald-500/50 pl-2" if is_critical else "pl-3"
    label_style = "text-emerald-400 font-bold uppercase tracking-wider text-xs" if is_critical else "text-slate-400 font-normal uppercase tracking-wider text-xs"

    return f"""
    <div class="{row_border}">
        <div class="flex justify-between text-sm mb-1 font-semibold">
            <span class="text-emerald-400">{val_a:.2f}</span>
            <span class="{label_style}">{label}</span>
            <span class="text-cyan-400">{val_b:.2f}</span>
        </div>
        <div class="flex h-3 bg-slate-800 rounded-full overflow-hidden">
            <div class="bg-emerald-500" style="width: {pct_a:.1f}%"></div>
            <div class="bg-cyan-500 ml-auto" style="width: {pct_b:.1f}%"></div>
        </div>
    </div>"""

def clean_url_slug(name):
    return name.lower().replace(" ", "-").replace(".", "").replace("'", "")


# ==========================================
# 4. MASTER COMPRESSION PIPELINE
# ==========================================
def execute_matrix_pipeline():
    os.makedirs('public/vs', exist_ok=True)
    players_pool = fetch_live_fpl_pool()
    if not players_pool:
        print("Data ingestion empty. Execution pipeline suspended.")
        return

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    generated_links = []

    for player_a, player_b in itertools.combinations(players_pool, 2):
        slug_a = clean_url_slug(player_a['name'])
        slug_b = clean_url_slug(player_b['name'])
        filename = f"{slug_a}-vs-{slug_b}.html"
        filepath = os.path.join('public/vs', filename)
        
        stat_rows_html = ""
        # Setup which positions get which stats highlighted (2=Def, 3=Mid, 4=Fwd)
        metrics_config = [
            {"key": "goals", "label": "Goals", "critical_roles": [4]},
            {"key": "xg", "label": "Expected Goals (xG)", "critical_roles": [4]},
            {"key": "assists", "label": "Assists", "critical_roles": [3]},
            {"key": "xa", "label": "Expected Assists (xA)", "critical_roles": [3]},
            {"key": "clean_sheets", "label": "Clean Sheets", "critical_roles": [2]},
            {"key": "influence", "label": "FPL Influence Index", "critical_roles": [2, 3]}
        ]

        for metric in metrics_config:
            is_critical = (player_a['position_id'] in metric["critical_roles"]) or (player_b['position_id'] in metric["critical_roles"])
            stat_rows_html += build_metric_row(metric["label"], player_a[metric["key"]], player_b[metric["key"]], is_critical)

        verdict = f"Comparing <strong>{player_a['name']}</strong> ({player_a['position_name']}) and <strong>{player_b['name']}</strong> ({player_b['position_name']}). "
        if player_a['total_points'] > player_b['total_points']:
            verdict += f"Tactically, {player_a['name']} holds the seasonal form advantage in the selection pool."
        else:
            verdict += f"Tactically, {player_b['name']} maintains a higher overall efficiency index this season."

        replacements = {
            '{{PLAYER_A}}': player_a['name'],
            '{{PLAYER_B}}': player_b['name'],
            '{{PLAYER_A_POS}}': player_a['position_name'],
            '{{PLAYER_B_POS}}': player_b['position_name'],
            '{{VERDICT_TEXT}}': verdict,
            '{{STAT_ROWS}}': stat_rows_html,
            '{{TIMESTAMP}}': timestamp
        }
        
        compiled_page = HTML_TEMPLATE
        for placeholder, value in replacements.items():
            compiled_page = compiled_page.replace(placeholder, value)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(compiled_page)
            
        generated_links.append({
            'anchor_text': f"{player_a['name']} ({player_a['position_name']}) vs {player_b['name']} ({player_b['position_name']})",
            'url': f"vs/{filename}"
        })

    build_central_index(generated_links, timestamp)
    generate_sitemap(generated_links, base_url="https://football-matrix.disillusioneddev.workers.dev")

def build_central_index(links, timestamp):
    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="c_K6M_6ZUJTCpaExzxn5HyzwgyupoiwBwC2TUBi5RRg" />
    <title>DEBATE.FC | Head-to-Head Player Analytics Engine</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #f8fafc; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #34d399; text-align: center; font-size: 2.5rem; font-weight: 900; letter-spacing: -0.025em; }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; margin-top: 40px; }}
        .card {{ background: #1e293b; padding: 14px; border-radius: 10px; text-align: center; border: 1px solid #334155; text-decoration: none; color: #f8fafc; font-weight: 500; transition: all 0.2s; }}
        .card:hover {{ border-color: #34d399; background: #1e293b; transform: translateY(-2px); box-shadow: 0 10px 15px -3px rgba(52, 211, 153, 0.1); }}
        .footer {{ text-align: center; font-size: 0.8rem; color: #64748b; margin-top: 60px; border-top: 1px solid #334155; padding-top: 20px; }}
    </style>
</head>
<body>
    <h1>📊 DEBATE.FC DATA CORE</h1>
    <p style="text-align:center; color:#94a3b8;">Select a long-tail search matrix connection node below to inspect performance indicators.</p>
    <div class="grid">
    """
    for link in links:
        index_html += f'        <a class="card" href="{link["url"]}">{link["anchor_text"]}</a>\n'
        
    index_html += f"""    </div>
    <div class="footer">Site compiled automatically on {timestamp} UTC via Live API Infrastructure.</div>
</body>
</html>"""

    with open('public/index.html', 'w', encoding='utf-8') as f:
        f.write(index_html)
    print(f"Successfully generated main landing directory with {len(links)} long-tail nodes.")

def generate_sitemap(links, base_url):
    print("🤖 Starting automated sitemap generation...")
    today = datetime.now().strftime("%Y-%m-%d")
    xml_content = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        '  <url>',
        f'    <loc>{base_url}/</loc>',
        f'    <lastmod>{today}</lastmod>',
        '    <changefreq>daily</changefreq>',
        '    <priority>1.0</priority>',
        '  </url>'
    ]
    for link in links:
        xml_content.append('  <url>')
        xml_content.append(f'    <loc>{base_url}/{link["url"]}</loc>')
        xml_content.append(f'    <lastmod>{today}</lastmod>')
        xml_content.append('    <changefreq>weekly</changefreq>')
        xml_content.append('    <priority>0.8</priority>')
        xml_content.append('  </url>')
    xml_content.append('</urlset>')
    
    with open(os.path.join("public", "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(xml_content))
    print(f"✅ sitemap.xml successfully created with {len(links) + 1} indexed assets!")

if __name__ == "__main__":
    execute_matrix_pipeline()
